# Generated by Django 3.2.4 on 2021-06-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_email_orders_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeaddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=111)),
                ('home_address', models.CharField(max_length=111)),
            ],
        ),
    ]
