# Generated by Django 3.2.4 on 2021-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_homeaddr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='adminReply',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homeaddr',
            name='user',
            field=models.CharField(max_length=90),
        ),
    ]
